name: sahel_net
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  flutter_svg: ^2.0.8
  smooth_page_indicator: ^1.1.0
  card_swiper: ^3.0.1
  cached_network_image: ^3.3.0
  step_progress_indicator: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  animated_bottom_navigation_bar: ^1.3.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.5.0
  #  photo_view: ^0.14.0
  url_launcher: ^6.1.14
  dartz: ^0.10.1
  bloc: ^8.1.2
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  get_it: ^7.7.0
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  device_preview: ^1.1.0
  http: ^1.2.1
  share_plus: ^10.0.0
  flutter_rating_bar: ^4.0.1
  sticky_headers: ^0.3.0+2
  connectivity_plus: ^6.0.3
  flutter_otp_text_field: ^1.1.2+1
  lottie: ^3.1.0
  cherry_toast: ^1.10.0
  animator: ^3.3.0
  animations: ^2.0.11
  image_picker: ^1.1.2
  image: ^4.2.0
  dotted_border: ^2.1.0
  fl_chart: ^0.69.0
  permission_handler: ^11.3.1
  image_cropper: ^8.0.2
  skeletonizer: ^1.4.2
  geolocator: ^13.0.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  fonts:
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-VariableFont_wght.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
          weight: 700
    - family: Qahiri
      fonts:
        - asset: assets/fonts/Qahiri-Regular.ttf
          weight: 400
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada-Regular.ttf
          weight: 400

  assets:
    - assets/
    - assets/fonts/
    - assets/images/







