// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBniV4eDSpweP8WJr8Kgt_RRnsKI1s1fhs',
    appId: '1:560153429134:web:2a899b2884e93d584975df',
    messagingSenderId: '560153429134',
    projectId: 'easy-for-you-b55c2',
    authDomain: 'easy-for-you-b55c2.firebaseapp.com',
    storageBucket: 'easy-for-you-b55c2.appspot.com',
    measurementId: 'G-V91TMNZBN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpkAoE9LzP0lgk08PIP5U-NuAAekYrrI',
    appId: '1:560153429134:android:032cb198128992514975df',
    messagingSenderId: '560153429134',
    projectId: 'easy-for-you-b55c2',
    storageBucket: 'easy-for-you-b55c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT9lq6Ql6PqDv-aFZtXaPl0IhqyragWyo',
    appId: '1:560153429134:ios:1fec57b8718b4d454975df',
    messagingSenderId: '560153429134',
    projectId: 'easy-for-you-b55c2',
    storageBucket: 'easy-for-you-b55c2.appspot.com',
    iosBundleId: 'com.example.sahelNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT9lq6Ql6PqDv-aFZtXaPl0IhqyragWyo',
    appId: '1:560153429134:ios:1fec57b8718b4d454975df',
    messagingSenderId: '560153429134',
    projectId: 'easy-for-you-b55c2',
    storageBucket: 'easy-for-you-b55c2.appspot.com',
    iosBundleId: 'com.example.sahelNet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBniV4eDSpweP8WJr8Kgt_RRnsKI1s1fhs',
    appId: '1:560153429134:web:d6a6f6cde669a8d54975df',
    messagingSenderId: '560153429134',
    projectId: 'easy-for-you-b55c2',
    authDomain: 'easy-for-you-b55c2.firebaseapp.com',
    storageBucket: 'easy-for-you-b55c2.appspot.com',
    measurementId: 'G-SJH3XPCZWR',
  );
}
